-- Contacts Schema

-- !Ups
CREATE TABLE "CONTACTS"(
	"ID" UUID PRIMARY KEY,
	"FIRST_NAME" VARCHAR(255),
	"MIDDLE_NAME" VARCHAR(255),
	"LAST_NAME" VARCHAR(255),
	"EMAIL" VARCHAR(255) NOT NULL,
	"PHONE_NUMBER" VARCHAR(255) NOT NULL,
	"CREATED_AT" TIMESTAMP
);

-- !Downs
DROP TABLE "CONTACTS";