-- !Ups

CREATE TABLE "USERS"(
	"ID" UUID PRIMARY KEY,
	"NAME" VARCHAR(255),
	"EMAIL" VARCHAR(255) NOT NULL,
	"PASSWORD" VARCHAR(255) NOT NULL,
	"CREATED_AT" TIMESTAMP
);

ALTER TABLE "CONTACTS" ADD COLUMN "USER_ID" UUID;

ALTER TABLE "CONTACTS" ADD CONSTRAINT "FK_CONTACTS_USER" 
FOREIGN KEY("USER_ID") REFERENCES "USERS"("ID") ON DELETE CASCADE;


-- !Downs
ALTER TABLE "CONTACTS" DROP COLUMN "USER_ID";

DROP TABLE "USERS";