-- !Ups
CREATE TABLE "GROUPS"(
	"ID" UUID PRIMARY KEY,
	"USER_ID" UUID REFERENCES "USERS"("ID") ON DELETE CASCADE,
	"NAME" VARCHAR(255),
	"CREATED_AT" TIMESTAMP
);

ALTER TABLE "CONTACTS" ADD COLUMN "GROUP_ID" UUID; 

ALTER TABLE "CONTACTS" ADD CONSTRAINT "FK_CONTACTS_GROUP" 
FOREIGN KEY("GROUP_ID") REFERENCES "GROUPS"("ID") ON DELETE CASCADE;

-- !Downs
ALTER TABLE "CONTACTS" DROP COLUMN "GROUP_ID";

DROP TABLE "GROUPS";